# Generated by Django 5.1.5 on 2025-02-04 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=30)),
                ('ano', models.CharField(max_length=4)),
                ('preco', models.FloatField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Vendedor',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.FloatField()),
                ('data_venda', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.veiculo')),
            ],
            options={
                'verbose_name': 'Venda',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_pagamento', models.DateTimeField()),
                ('tipo_pag', models.CharField(max_length=100)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.venda')),
            ],
            options={
                'verbose_name': 'Pagamento',
            },
        ),
    ]
