# Generated by Django 5.1.5 on 2025-02-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='saldo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
