# Generated by Django 5.1.5 on 2025-02-05 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_vendedor_options_venda_vendedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venda',
            new_name='Venda_Pendente',
        ),
        migrations.AlterModelOptions(
            name='venda_pendente',
            options={'verbose_name': 'Vendas Pendente'},
        ),
    ]
