# Generated by Django 5.1.5 on 2025-02-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_pagamento_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='saldo',
            field=models.FloatField(blank=True),
        ),
    ]
